language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=800044e0eb011d27318d993c39619c8e529c2f6af7ebb239567dc8b1b9983452
    - NODE_ENV=test
node_js:
  - "8.12.0"
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run coveralls
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
